# Generated by Django 4.2.7 on 2023-11-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='edit_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
